elgopher/yala

adapter/log15adapter/log15adapter.go
adapter/logrusadapter/logrus.go
adapter/printer/printer.go
adapter/zapadapter/zapadapter.go
adapter/zerologadapter/zerolog.go

Avoid embedding interfaces without name.

Adapters should now have underlying logger methods

---

README.md
adapter/contextservice/_example/main.go
adapter/glogadapter/_example/main.go
adapter/log15adapter/_example/main.go
adapter/logrusadapter/_example/main.go
adapter/printer/_example/main.go
adapter/zapadapter/_example/main.go
adapter/zapadapter/zapadapter.go
adapter/zerologadapter/_example/main.go
logger/local.go
logger/logger.go
logger/logger_test.go

The use of formatting functions (such as logger.Infof) does not fit well with structured logging. Developer should use fields instead of formatting messages by hand, because fields are better when searching. Also when messages are constants, they compress better.

Remove formatting functions

---

README.md
adapter/glogadapter/glog.go
adapter/log15adapter/log15adapter.go
adapter/logrusadapter/logrus.go
adapter/zapadapter/zapadapter.go
logger/logger_test.go

This change does not modify API, just internal details.

Rename Adapters method receivers from s to a

---

README.md

TO avoid confusion with logger.Logger struct.

[README] Rename Logger to ImaginaryLogger

---

adapter/contextadapter/_example/main.go
adapter/contextadapter/contextadapter.go
adapter/glogadapter/_example/main.go

Current implementation of contextadapter is too limiting. It does not support passing all kinds of loggers via context (only yala adapter).  But in reality many applications use their own implementations.
This commit ads possibility to specify custom behaviour for extracting logger.Adapter out of  context.Context.

Refactor contextadapter

---

logger/adapter.go
logger/logger_test.go
logger/noop.go

Print warning message that global logger was not set. This is a hint for the library user, that the lib is trying to log something, but logging is disabled.

Add warning that no global logger is set

---

adapter/printer/_example/main.go
adapter/printer/printer.go
adapter/printer/printer_test.go

This commit improves logfmt formatting for values which:
* have quote, backslash, space or equal sign
* are nil
Fixes #19

[printer] improve logmt formatting in printer

---

logger/adapter.go
logger/global.go
logger/logger.go
logger/logger_test.go

This change does not break the API.
The new logger.global struct is a logger which adapter can be changed anytime.

[refactor] create global logger

---

README.md
adapter/contextadapter/_example/main.go
adapter/glogadapter/_example/main.go
adapter/internal/benchmark/benchmark.go
adapter/log15adapter/_example/main.go
adapter/logrusadapter/_example/main.go
adapter/printer/_example/main.go
adapter/zapadapter/_example/main.go
adapter/zerologadapter/_example/main.go
logger/adapter.go
logger/global.go
logger/logger.go
logger/logger_bench_test.go
logger/logger_concurrency_test.go
logger/logger_test.go
logger/noop.go

This struct is useful for defining global loggers in your libaries.
This commit also removes global logger from logger package. Sharing logger between multiple libraries have limitations:
* no way to disable logging for particular libs
* no way to provide different fields for particular libs (for example the name of logger)

[breaking change] Create logger.Global logger

---

.github/workflows/go.yml

Using 3 different operating systems does not really make sense, because yala is not using os-specific calls. It will be better to support multiple versions of Go instead.

[github] Run Go tests using multiple versions of Go

---

.github/workflows/go.yml
logger/global.go

There is a chance that using two goroutines simultaneously, on an uninitialized global logger may lead to a bad outcome. One goroutine may want to log something, other want to set the adapter. The first one will realise that no adapter is set, the second one will set the adapter and then the first one will set the noop adapter. So eventually setting the adapter to specific implementation will not work.

[bugfix] Fix race condition in logger.Global

---

Makefile
adapter/glogadapter/_example/main.go
adapter/internal/benchmark/benchmark.go
adapter/log15adapter/_example/main.go
adapter/logrusadapter/_example/main.go
adapter/printer/_example/main.go
adapter/zapadapter/_example/main.go
adapter/zerologadapter/_example/main.go
logger/_examples/contextlogger/main.go
logger/_examples/filter/main.go
logger/_examples/tags/main.go
logger/global.go
logger/local.go
logger/logger_concurrency_test.go
logger/logger_test.go

At the moment logger.Local(adapter) is a constructor creating LocalLogger instance. This constructor does not do anything special. That's why it is not needed.
Also, other structures in yala (adapters) are initialized using struct literal. So using a function constructor is not very intuitive.
Also, global logger is named logger.Global. So local one should be named logger.Local.

Convert logger.Local from function to struct

---

adapter/logfmt/logfmt.go
adapter/logfmt/logfmt_test.go
logger/_examples/reuse/main.go

Change formatting of numbers, slices, maps and structs.
Use fmt.Sprintf("%+v") instead of fmt.Sprintf("%s")

[logfmt] Change formatting

---

adapter/glogadapter/glog.go

glog provides InfoDepth function which acts as Info but uses depth to determine which call frame to log. Yala's logger.Entry has a SkippedCallerFrames which can be used as depth.

[glog] Use glog depth

---

adapter/console/console.go
adapter/console/console_test.go
adapter/internal/benchmark/RESULTS.md
adapter/logadapter/_example/main.go
adapter/logadapter/logadapter.go
adapter/logadapter/logadapter_bench_test.go
adapter/printer/printer.go
adapter/printer/printer_test.go

At the moment the caller printed in logs is some frame from yala internals, not the real caller.
Change Printer.Println method signature, so the logadapter can pass the depth. Plus Println accepts varargs even though it is not used. Using string will be faster (less allocations).

[log] Fix caller information presented by logadapter

---

README.md
adapter/log15adapter/log15_test.go
adapter/printer/printer.go
logger/_examples/levelfilter/main.go
logger/adapter.go
logger/logger_test.go

This change will make it possible to compare levels. It is useful in adapters filtering by minimum level.
The old string representation will be available via new method `Level.String()`

Change type of logger.Level to int8

---

README.md
adapter/console/_example/main.go
adapter/glogadapter/_example/main.go
adapter/internal/benchmark/benchmark.go
adapter/log15adapter/_example/main.go
adapter/logadapter/_example/main.go
adapter/logrusadapter/_example/main.go
adapter/zapadapter/_example/main.go
adapter/zerologadapter/_example/main.go
logger/_examples/reuse/main.go
logger/_examples/tags/main.go
logger/global.go
logger/local.go
logger/logger.go
logger/logger_bench_test.go
logger/logger_concurrency_test.go
logger/logger_test.go

context.Context should not be retained in other structures, because it makes user programs more complicated. context.Context should be passed to log methods such as Info, Debug, Warn and Error.

Move context.Context parameter to Info method

---

adapter/logadapter/logadapter.go
adapter/logadapter/logadapter_test.go

logadapter.Adapter() func accepts *log.Logger which can be nil. This adapter should support nil logger and don't log anything in such case.

[log] Don't panic when *log.Logger is nil

---

logger/adapter_mock_test.go
logger/global.go
logger/logger_test.go

This method is similar to logger.Logger.WithSkippedCallerFrame()
WithSkippedCallerFrame creates a new child logger with one more skipped caller frame. This function is handy when you want to write your own logging helpers.

Add Global.WithSkippedCallerFrame

---

adapter/logrusadapter/_example/main.go
adapter/logrusadapter/logrus.go
adapter/logrusadapter/logrus_bench_test.go
adapter/logrusadapter/logrus_test.go

So far, only *logrus.Entry was accepted. But sometimes end user would prefer to pass *logrus.Logger directly.
This commit also renames Adapter.Entry field to Adapter.Logger.

[logrus] Accept also *logrus.Logger in logrus adapter

---

adapter/glogadapter/glog_test.go
adapter/internal/adaptertest/adaptertest.go
logger/_examples/caller/main.go
logger/_examples/tags/main.go
logger/adapter.go
logger/global.go
logger/logger.go
logger/logger_test.go

This method is not needed because the end result is the same as built-in append function.

Remove Entry.With method

---

adapter/glogadapter/glog_test.go
adapter/internal/adaptertest/adaptertest.go
logger/_examples/caller/main.go
logger/_examples/tags/main.go
logger/adapter.go
logger/global.go
logger/logger.go
logger/logger_test.go

This reverts commit 80d8c30e
It turns out that this change is unsafe from concurrency perspective.

Revert "Remove Entry.With method"

---

logger/noop.go

Wrong caller information (file and line number) is used when printing warning about disabled global logger.

[bug] Invalid caller reported when logging is disabled

---

logger/global.go

That instance of logger.Global should not be copied.

[doc] Add info to logger.Global

---

README.md
adapter/console/_example/main.go
adapter/glogadapter/_example/main.go
adapter/internal/benchmark/benchmark.go
adapter/log15adapter/_example/main.go
adapter/logadapter/_example/main.go
adapter/logrusadapter/_example/main.go
adapter/zapadapter/_example/main.go
adapter/zerologadapter/_example/main.go
logger/_examples/caller/main.go
logger/_examples/rename/main.go
logger/_examples/reuse/main.go
logger/_examples/tags/main.go
logger/adapter.go
logger/adapter_test.go
logger/global.go
logger/logger.go
logger/logger_bench_test.go
logger/logger_test.go

Right now developer can use fluent-interface API to log message with fields, for example:
```go
log.With("key1","value").
With("key2","value").
Info(ctx, "message")
```
For some such design is not intuitive. They prefer to pass fields directly as an Info method parameter. Preferably a map. For example:
```go
log.InfoFields(ctx, "message", logger.Fields{
"key1": "value",
"key2": "value",
})
```
Also, the performance of fluent-interface design is not very high. Each With method call creates a new instance of logger with additional field which costs 1 allocation (for normal logger) and 2 allocations (for global one). Most of the time, such logger will be discarded soon (in the very same method), so allocation could be avoided.
The proposed new logger methods can simplify the use of logger …

Add new ***Fields methods
